spring.application.name=backend

spring.datasource.url = ${POSTGRES_URL}
spring.datasource.username = postgres
spring.datasource.password = ${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.google.client-id= ${GOOGLE_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


brevo.api.key=${BREVO_KEY}
brevo.sender.email=lutadesahil@gmail.com
brevo.sender.name=Synapz AI

supabase.url=${SUPABASE_URL}
supabase.service.key=${SUPABASE_SECRET}
supabase.bucket=profile-images

gemini.api.key=${GEMINI_KEY}
gemini.model=gemini-2.5-flash

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRY}

razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_SECRET}

server.port=${PORT:8080}
